### ISSUE TITLE
Got exception: invalid load key, '<'. 

### ISSUE THREAD

**Issue by erhathaway** [DPS2022/diffusion-posterior-sampling#2]
While running the below task (and others) I get the error `Got exception: invalid load key, '<'. ` but the program proceeds to execute.

```
python3 sample_condition.py --model_config=configs/model_config.yaml --diffusion_config=configs/diffusion_config.yaml --task_config=configs/gaussian_deblur_config.yaml
````

**Comment by kskali-kali** [comment]
Hello friend, what is the reason for my problem?
：
“
Traceback (most recent call last):
  File "C:\Users\29622\Desktop\学术论文\代码\2022_diffusion-posterior-sampling-main\diffusion-posterior-sampling-main\sample_condition.py", line 123, in <module>
    main()
  File "C:\Users\29622\Desktop\学术论文\代码\2022_diffusion-posterior-sampling-main\diffusion-posterior-sampling-main\sample_condition.py", line 34, in main
    args = parser.parse_args()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 1896, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 1929, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 2178, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 2663, in error
    self.print_usage(_sys.stderr)
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 2631, in print_usage
    self._print_message(self.format_usage(), file)
                        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 2597, in format_usage
    return formatter.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 287, in format_help
    help = self._root_section.format_help()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 217, in format_help
    item_help = join([func(*args) for func, args in self.items])
                      ^^^^^^^^^^^
  File "C:\Users\29622\anaconda3\envs\zfqpytorch\Lib\argparse.py", line 343, in _format_usage
    assert ' '.join(pos_parts) == pos_usage
           ^^^^^^^^^^^^^^^^^^^^^^
           
AssertionError
”
Please！！！！
